#################################################################################################################
# Define the settings for the rook-ceph cluster with common settings for a small test cluster.
# All nodes with available raw devices will be used for the Ceph cluster. One node is sufficient
# in this example.

# For example, to create the cluster:
#   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#   kubectl create -f cluster-test.yaml
#################################################################################################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook-ceph # namespace:cluster
data:
  config: |
    [global]
    osd_pool_default_size = 1
    mon_warn_on_pool_no_redundancy = false
    bdev_flock_retry = 20
    bluefs_buffered_io = false
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph-cluster
  namespace: rook-ceph # namespace:cluster
spec:
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
    allowUnsupported: true
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: true
    #deviceFilter:
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
        timeout: 600s
  disruptionManagement:
    managePodBudgets: true
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: device-health-metrics
  namespace: rook-ceph # namespace:cluster
spec:
  name: device_health_metrics
  failureDomain: host
  replicated:
    size: 1
    requireSafeReplicaSize: false
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: HelmRepository
# metadata:
#   name: rook-release
#   namespace: rook-ceph
# spec:
#   interval: 1m
#   url: https://charts.rook.io/release
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: rook-ceph
#   namespace: rook-ceph
# spec:
#   chart:
#     spec:
#       chart: rook-ceph
#       sourceRef:
#         kind: HelmRepository
#         name: rook-release
#         namespace: rook-ceph
#       version: 1.8.3
#   interval: 1m0s
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: rook-ceph-cluster
#   namespace: rook-ceph
# spec:
#   chart:
#     spec:
#       chart: rook-ceph-cluster
#       sourceRef:
#         kind: HelmRepository
#         name: rook-release
#         namespace: rook-ceph
#       version: 1.8.3
#   interval: 1m0s
#   values:
#     operatorNamespace: rook-ceph
