---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    team: DevOps
    istio-injection: enable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1m
  url: https://helm.goharbor.io
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cephfs-big-pvc
#   namespace: kube-system
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: rook-cephfs
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cephfs-medium-pvc
#   namespace: kube-system
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: rook-cephfs
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cephfs-small-pvc
#   namespace: kube-system
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: rook-cephfs
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: harbor
#   namespace: harbor
# spec:
#   chart:
#     spec:
#       chart: harbor
#       sourceRef:
#         kind: HelmRepository
#         name: harbor
#       version: 1.8.1
#   interval: 1m0s
#   values:
#     portal:
#       replicas: 2
#     core:
#       replicas: 2
#     jobservice:
#       replicas: 2
#     registry:
#       replicas: 2
#     chartmuseum:
#       replicas: 2
#     clair:
#       replicas: 2
#     notary:
#       server:
#         replicas: 2
#       signer:
#         replicas: 2
#     persistence:
#       persistentVolumeClaim:
#         registry:
#           storageClass: rook-cephfs
#           accessMode: ReadWriteMany
#         chartmuseum:
#           storageClass: rook-cephfs
#           accessMode: ReadWriteMany
#         jobservice:
#           storageClass: rook-cephfs
#           accessMode: ReadWriteMany
