---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    team: DevOps
    istio-injection: enable
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-harbor-registry
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-harbor-chartmuseum
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-harbor-jobservice
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-harbor-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-harbor-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-harbor-trivy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1m
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: 1.8.1
  interval: 1m0s
  values:
    portal:
      replicas: 2
    core:
      replicas: 2
    jobservice:
      replicas: 2
    registry:
      replicas: 2
    chartmuseum:
      replicas: 2
    clair:
      replicas: 2
    notary:
      server:
        replicas: 2
      signer:
        replicas: 2
    persistence:
      persistentVolumeClaim:
        registry:
            existingClaim: "cephfs-harbor-registry"
        chartmuseum:
            existingClaim: "cephfs-harbor-chartmuseum"
        jobservice:
            existingClaim: "cephfs-harbor-jobservice"
        database:
          existingClaim: "rbd-harbor-database"
        redis:
          existingClaim: "rbd-harbor-redis"
        trivy:
          existingClaim: "rbd-harbor-trivy"
