apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-cert
  namespace: shipwright-build
data:
  labasa-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFnTCCA4WgAwIBAgIUHp9BnVBvFDvwkzJEqP4+mRtTxMEwDQYJKoZIhvcNAQEL
    BQAwXjELMAkGA1UEBhMCQlIxEjAQBgNVBAgMCVNhbyBQYXVsbzESMBAGA1UEBwwJ
    U2FvIFBhdWxvMQ8wDQYDVQQKDAZMYWIgU0ExFjAUBgNVBAsMDUlUIERlcGFydG1l
    bnQwHhcNMjIwMjAxMDA0NDI0WhcNMjMwMjAxMDA0NDI0WjBeMQswCQYDVQQGEwJC
    UjESMBAGA1UECAwJU2FvIFBhdWxvMRIwEAYDVQQHDAlTYW8gUGF1bG8xDzANBgNV
    BAoMBkxhYiBTQTEWMBQGA1UECwwNSVQgRGVwYXJ0bWVudDCCAiIwDQYJKoZIhvcN
    AQEBBQADggIPADCCAgoCggIBAMJgqawW3SBGUsLIfeqgOdI5lSHiZkjz5jcObRNq
    AdWUG5AkHn6YsV6XZjM0R2IywHn01p8IJ4AVTbXZkCF0i441thOwvtPlaT4pxG/m
    3wmuxVFL3N3jCBeR/zht38FHMPspT2j0EmcnoXJy7LFqiLHsysakQwV4flqcPDEH
    mrMq0FA5SI7yZDAkrPfT532vrDLbbTxdPjAxO1O0/712TXQBFNpSY1zPNUrAby3p
    4ALGfN+sbtXfqLSVn+zlGgR/mvsYb1nKv/aXLj9oAQRumwB2t8H6c/ZISZvxWel7
    f02YUHYEhmTnVI9ctxQCCMz0DzfTbnHKkSGkciGmgG588OZvFvbaBowWk/t7eUEq
    HJjse/VKUml77UNA4jVeJFKasngJzBVAdpBwvRjh9PKGGc17qvGgprsIW2PIF70F
    zSVzgqi0QJr36O7IyBNpyrYUIVhM7kn21dbJKpgRcncVOAffeKwrBSDM2TAlOj4T
    lhp4AcA9GJCjqZ31IXhsAVucoBTpA4tEWyfhFEfPxLntY4oNYqETaZ1ru/hmt/M2
    UA+pfuRUKidTYkMMbzMDCIWhZ9lC9nSEKS0YI8pl3mzbi7j0zUmwbDeFQab9Pg7m
    0t3PmGIXZfxDuuvraMxoVRuSO4IcsQyoLbzMk2LyLOWMXKUH+iF11sVdMR9fzMjw
    2hc/AgMBAAGjUzBRMB0GA1UdDgQWBBSyvkFU1ePV9s+K6f1nCtOxTd3KDTAfBgNV
    HSMEGDAWgBSyvkFU1ePV9s+K6f1nCtOxTd3KDTAPBgNVHRMBAf8EBTADAQH/MA0G
    CSqGSIb3DQEBCwUAA4ICAQC3PwFtL5F0koYBaovzLntaVz5xn1ZbxSEDFSKa+1z3
    20wUxScGHHw67jaPBXPCf6qZU86I1VQmckLUjewZMSEqGu8ojmYHmLlmznhmijov
    vF6V0jDrApqVvRYxOUvI3AoLK93ouKugz9eux0t2hn6PMKBizvV/PfYt/TwnvrTP
    NcnOZz9EYWWS0v3pZzXdr9zuDaJ89jgQiIRo4U6y5NRiC3PJpx1MM4c/NS4DnRvV
    98PhPatpXXlLo0aLeeQhl7MxdQwbx7B7YcRlQnJdMBFnlf35q6xhqQnWQi6jzM4v
    zgrWnw4ILeiO9X5WkWryJt8huuGqibkSAd0b5lZw80/mnW1bJMIXZJTY7y6i6HrY
    fSgj0+l2jSmTE657xEl4RjbdOXO0qswYR3RvwBQglvotDgV54YXHlGKT5dEWl1fR
    jjTkf4e9ydstS8vmdxAqvQVInnVri8yOpErSflrVQeBq1jo+5g2/NFB5nB7zklSa
    2u9h2voYFZpER0LPrCJ+DU4c2Kf9jNEg54+OyWakZ8p8qgXqRZ9Gj9+FVqXc0Vtx
    6lMVza3NNvQifyfEMXkBDd1mAJ7LPS9m8/nspDFVZYz4rc6BQ1q9qTB5eMnzboCB
    VGbUsILfK+6tKMLyjMWx0dfnzwHJ078i7sto6hxMKhokGUVE0016KhxJcI8JRHqi
    hA==
    -----END CERTIFICATE-----
